# Written assuming ubuntu 16.04 server
---
- hosts: all
  gather_facts: yes

  tasks:

    - name: "get linux signing key"
      become: yes
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    # update manually and install linux-image-extra-$(uname -r) manually after reboot to get new kernel modules
    #- name: "updates"
    #  become: true
    #  apt:
    #    update_cache: yes
    #    upgrade: dist

    - name: "install pre-requisites"
      become: yes
      apt: "name={{ item }} state=installed"
      with_items:
        - git
        - p7zip
        - build-essential
        - libreadline5
        - libreadline-dev
        - libusb-0.1-4
        - libusb-dev
        - libqt4-dev
        - perl
        - pkg-config
        - wget
        - ncurses-dev
        - libncurses5-dev
        - gcc-arm-none-eabi
        - libstdc++-arm-none-eabi-newlib

    - name: "get kernel release"
      shell: uname -r | xargs
      register: kernel_release

    - name: "install linux-image-extra so that cdc_acm kernel module is available to proxmark3.  Creates /dev/ttyACM0"
      become: yes
      apt: "name=linux-image-extra-{{ kernel_release.stdout }}"
      state: installed

    - name: "git clone source"
      become: no
      git:
        repo: https://github.com/proxmark/proxmark3.git
        dest: ~/proxmark3
        depth: 1
        version: master
        force: yes

    - name: "setup usb udev rules"
      become: yes
      copy:
        src: ~/proxmark3/driver/77-mm-usb-device-blacklist.rules
        dest: /etc/udev/rules.d/77-mm-usb-device-blacklist.rules
        owner: root
        group: root
        mode: 0644

    - name: "udevadm reload"
      become: yes
      shell: "udevadm control --reload-rules"

    - name: "make all proxmark3"
      become: no
      shell: "make all"
      args:
        chdir: ~/proxmark3
